name: Makefile CI

on:
  push:
    branches: [ "master", "dev" ]
  pull_request:
    branches: [ "master", "dev" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with: 
        submodules: recursive
      
    - name: Install dependencies
      run: | 
        make
      
    - name: Run test
      run: make test
