name: Makefile CI

on:
  push:
    branches: [ "master", "dev" ]
  pull_request:
    branches: [ "master", "dev" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with: 
        submodules: recursive
      
    - name: Install dependencies
      run: | 
        sudo apt update
        sudo apt install libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev libxext-dev
        sudo apt install libglu1-mesa-dev freeglut3-dev mesa-common-dev
        make
      
    - name: Run test
      run: make test
